# Generated by Django 5.2.7 on 2025-10-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminusgpsnotificationscustomer',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
