# Generated by Django 5.2.7 on 2025-10-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminusgpsnotificationscustomer',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=64.99, help_text='Enter a dollar amount to charge the customer (not incl. tax) every period.', max_digits=9),
        ),
    ]
