# Generated by Django 5.2.7 on 2025-10-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0001_initial'),
        ('terminusgps_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscription',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='terminusgps_payments.subscription'),
        ),
    ]
