# Generated by Django 5.2.7 on 2025-11-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "terminusgps_notifications",
            "0002_alter_terminusgpsnotificationscustomer_subtotal",
        )
    ]

    operations = [
        migrations.RemoveField(
            model_name="terminusgpsnotificationscustomer", name="resource_id"
        ),
        migrations.RemoveField(
            model_name="wialonnotification", name="trigger"
        ),
        migrations.AddField(
            model_name="wialonnotification",
            name="resource_id",
            field=models.PositiveBigIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wialonnotification",
            name="trigger_parameters",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="wialonnotification",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("geozone", "Geofence"),
                    ("address", "Address"),
                    ("speed", "Speed"),
                    ("alarm", "Alarm"),
                    ("digital_input", "Digital input"),
                    ("msg_param", "Parameter in a message"),
                    ("sensor_value", "Sensor value"),
                    ("outage", "Connection loss"),
                    ("interposition", "Interposition of units"),
                    ("msgs_counter", "Excess of messages"),
                    ("route_control", "Route progress"),
                    ("driver", "Driver"),
                    ("trailer", "Trailer"),
                    ("service_interals", "Maintenance"),
                    ("fuel_filling", "Fuel filling/battery charge"),
                    ("fuel_theft", "Fuel drain/theft"),
                    ("health_check", "Health check"),
                ],
                default="sensor_value",
            ),
        ),
        migrations.AlterField(
            model_name="wialonnotification",
            name="unit_list",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
