# Generated by Django 5.2.7 on 2025-10-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0002_alter_customer_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='max_sms_count',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='customer',
            name='max_voice_count',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='voice_count',
            field=models.IntegerField(default=0),
        ),
    ]
