# Generated by Django 5.2.7 on 2025-10-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0003_customer_max_sms_count_customer_max_voice_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='max_sms_count',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='max_voice_count',
            field=models.IntegerField(default=500),
        ),
    ]
