# Generated by Django 5.2.7 on 2025-10-08 17:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0004_alter_customer_max_sms_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('params', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationControlSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_1_start', models.DateTimeField()),
                ('interval_2_start', models.DateTimeField()),
                ('interval_1_end', models.DateTimeField()),
                ('interval_2_end', models.DateTimeField()),
                ('day_of_month_mask', models.IntegerField()),
                ('month_mask', models.IntegerField()),
                ('day_of_week_mask', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_1_start', models.DateTimeField()),
                ('interval_2_start', models.DateTimeField()),
                ('interval_1_end', models.DateTimeField()),
                ('interval_2_end', models.DateTimeField()),
                ('day_of_month_mask', models.IntegerField()),
                ('month_mask', models.IntegerField()),
                ('day_of_week_mask', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('params', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='wialontoken',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='wialon_token',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='terminusgps_notifications.wialontoken'),
        ),
        migrations.AddField(
            model_name='notification',
            name='activation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='deactivation_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='desc',
            field=models.TextField(default=1, max_length=1024, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='lang',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='notification',
            name='max_alarms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='max_duration_prev',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='min_duration_alarm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.TextField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='wialon_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wialontoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='terminusgps_notifications.notificationaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='terminusgps_notifications.notificationschedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='trigger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='terminusgps_notifications.notificationtrigger'),
            preserve_default=False,
        ),
    ]
