# Generated by Django 5.2.7 on 2025-10-08 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0005_notificationaction_notificationcontrolschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WialonNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wialon_id', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('sms', 'SMS message'), ('voice', 'Voice message')], default='sms', max_length=5)),
                ('name', models.CharField(max_length=64)),
                ('text', models.TextField(max_length=1024)),
                ('activation_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('deactivation_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('max_alarms', models.PositiveIntegerField(default=0)),
                ('max_message_interval', models.PositiveIntegerField(default=0)),
                ('alarm_timeout', models.PositiveIntegerField(default=0)),
                ('control_period', models.PositiveIntegerField(default=0)),
                ('min_duration_alarm', models.PositiveIntegerField(default=0)),
                ('min_duration_prev', models.PositiveIntegerField(default=0)),
                ('lang', models.CharField(choices=[('en', 'English')], default='en', max_length=2)),
                ('flags', models.IntegerField(choices=[(0, 'Trigger for the first message'), (1, 'Trigger for every message'), (2, 'Disabled')], default=0)),
                ('timezone', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='terminusgps_notifications.customer')),
            ],
            options={
                'verbose_name': 'wialon notification',
                'verbose_name_plural': 'wialon notifications',
            },
        ),
        migrations.CreateModel(
            name='WialonUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wialon_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=64)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='terminusgps_notifications.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='trigger',
        ),
        migrations.DeleteModel(
            name='NotificationControlSchedule',
        ),
        migrations.AddField(
            model_name='wialonnotification',
            name='units',
            field=models.ManyToManyField(to='terminusgps_notifications.wialonunit'),
        ),
        migrations.DeleteModel(
            name='NotificationAction',
        ),
        migrations.DeleteModel(
            name='NotificationSchedule',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationTrigger',
        ),
    ]
