# Generated by Django 5.2.7 on 2025-10-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0006_wialonnotification_wialonunit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wialonnotification',
            old_name='lang',
            new_name='language',
        ),
    ]
