# Generated by Django 5.2.7 on 2025-10-08 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0007_rename_lang_wialonnotification_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wialonnotification',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='alarm_timeout',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1800)]),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='control_period',
            field=models.PositiveIntegerField(choices=[(0, 'Any time'), (60, 'Last minute'), (600, 'Last 10 minutes'), (3600, 'Last hour'), (86400, 'Last day')], default=0),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='max_message_interval',
            field=models.PositiveIntegerField(choices=[(0, 'Any time'), (60, '1 minute'), (600, '10 minutes'), (1800, '30 minutes'), (3600, '1 hour'), (21600, '6 hours'), (43200, '12 hours'), (86400, '1 day'), (864000, '10 days')], default=0),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='min_duration_alarm',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='min_duration_prev',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(86400)]),
        ),
    ]
