# Generated by Django 5.2.7 on 2025-10-08 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0008_remove_wialonnotification_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonnotification',
            name='activation_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='method',
            field=models.CharField(choices=[('sms', 'SMS'), ('voice', 'Voice')], default='sms', max_length=5),
        ),
    ]
