# Generated by Django 5.2.7 on 2025-10-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0009_alter_wialonnotification_activation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wialonnotification',
            name='flags',
            field=models.IntegerField(choices=[(0, 'Trigger on first message'), (1, 'Trigger on every message'), (2, 'Disabled')], default=0),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='name',
            field=models.CharField(help_text='Please provide a memorable name for your notification.', max_length=64),
        ),
    ]
