# Generated by Django 5.2.7 on 2025-10-09 18:46

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0010_alter_wialonnotification_flags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wialonnotification',
            name='trigger',
            field=models.CharField(choices=[('geozone', 'Geofence'), ('address', 'Address'), ('speed', 'Speed'), ('alarm', 'Alarm'), ('digital_input', 'Digital input'), ('msg_param', 'Parameter in a message'), ('sensor_value', 'Sensor value'), ('outage', 'Connection loss'), ('interposition', 'Interposition of units'), ('msgs_counter', 'Excess of messages'), ('route_control', 'Route progress'), ('driver', 'Driver'), ('trailer', 'Trailer'), ('service_interals', 'Maintenance'), ('fuel_filling', 'Fuel filling/battery charge'), ('fuel_theft', 'Fuel drain/theft'), ('health_check', 'Health check')], default='sensor_value', help_text='Please select a notification trigger.', max_length=64),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='activation_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Please provide a valid date and time to activate the notification.', null=True),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='alarm_timeout',
            field=models.PositiveIntegerField(default=0, help_text='Please provide the number of seconds before alarm timeout. 0 = never timeout.', validators=[django.core.validators.MaxValueValidator(1800)]),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='control_period',
            field=models.PositiveIntegerField(choices=[(0, 'Any time'), (60, 'Last minute'), (600, 'Last 10 minutes'), (3600, 'Last hour'), (86400, 'Last day')], default=0, help_text='Please provide the control period relative to current time.'),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='deactivation_time',
            field=models.DateTimeField(blank=True, default=None, help_text='Please provide a valid date and time to deactivate the notification. Leave this blank to never deactivate.', null=True),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='max_alarms',
            field=models.PositiveIntegerField(default=0, help_text='Please provide the maximum number of alarms. 0 = unlimited alarms.'),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='max_message_interval',
            field=models.PositiveIntegerField(choices=[(0, 'Any time'), (60, '1 minute'), (600, '10 minutes'), (1800, '30 minutes'), (3600, '1 hour'), (21600, '6 hours'), (43200, '12 hours'), (86400, '1 day'), (864000, '10 days')], default=0, help_text='Please provide the maximum allowed time between messages.'),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='method',
            field=models.CharField(choices=[('sms', 'SMS'), ('voice', 'Voice')], default='sms', help_text='Please select a notification method.', max_length=5),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='min_duration_alarm',
            field=models.PositiveIntegerField(default=0, help_text='Please provide the minimum duration of alarm state in seconds.', validators=[django.core.validators.MaxValueValidator(86400)]),
        ),
    ]
