# Generated by Django 5.2.7 on 2025-10-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0011_wialonnotification_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wialonnotification',
            name='trigger_parameters',
            field=models.JSONField(default=dict),
        ),
    ]
