# Generated by Django 5.2.7 on 2025-10-10 15:30

import terminusgps_notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0012_wialonnotification_trigger_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='max_sms_count',
            field=models.IntegerField(default=500, help_text='Please enter the maximum number of allowed sms messages for the customer in a single period.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='max_voice_count',
            field=models.IntegerField(default=500, help_text='Please enter the maximum number of allowed voice messages for the customer in a single period.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='resource_id',
            field=models.CharField(blank=True, default=None, help_text='Please provide an 8-digit Wialon resource id for notifications.', max_length=8, null=True, validators=[terminusgps_notifications.models.validate_is_digit]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sms_count',
            field=models.IntegerField(default=0, help_text='Please enter the current sms message count for the customer.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.0825, help_text='Please enter a tax rate for the customer.', max_digits=9),
        ),
        migrations.AlterField(
            model_name='customer',
            name='voice_count',
            field=models.IntegerField(default=0, help_text='Please enter the current voice message count for the customer.'),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='flags',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Trigger on every message'), (0, 'Trigger on first message'), (2, 'Disabled')], default=0),
        ),
    ]
