# Generated by Django 5.2.7 on 2025-10-10 15:31

import django.core.validators
import terminusgps_notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0013_alter_customer_max_sms_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='resource_id',
            field=models.CharField(blank=True, default=None, help_text='Please provide an 8-digit Wialon resource id for notifications.', max_length=8, null=True, validators=[terminusgps_notifications.models.validate_is_digit, django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='flags',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Trigger on first message'), (2, 'Disabled'), (1, 'Trigger on every message')], default=0),
        ),
    ]
