# Generated by Django 5.2.7 on 2025-10-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_notifications', '0014_alter_customer_resource_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wialonnotification',
            name='units',
        ),
        migrations.AlterField(
            model_name='customer',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=44.99, help_text='Please enter a dollar amount to charge the customer (+tax) every period.', max_digits=9),
        ),
        migrations.AlterField(
            model_name='wialonnotification',
            name='flags',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Disabled'), (0, 'Trigger on first message'), (1, 'Trigger on every message')], default=0),
        ),
        migrations.DeleteModel(
            name='WialonUnit',
        ),
        migrations.AddField(
            model_name='wialonnotification',
            name='units',
            field=models.CharField(blank=True, default=''),
        ),
    ]
